---
- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: /usr/local/bin/node_exporter

- name: Create Node Exporter systemd service file
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=ec2-user
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=default.target

- name: Start and enable Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes

- name: Configure Docker daemon for CloudWatch logs
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "awslogs",
        "log-opts": {
          "awslogs-region": "eu-west-1",
          "awslogs-group": "flask-app-logs",
          "awslogs-create-group": "true"
        }
      }
  notify: restart docker
