---
- name: Create Jenkins directory
  ansible.builtin.file:
    path: /opt/jenkins
    state: directory
    mode: '0755'

- name: Copy docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: /opt/jenkins/docker-compose.yml
    mode: '0644'

- name: Start Jenkins using Docker Compose
  ansible.builtin.command: /usr/local/bin/docker-compose up -d
  args:
    chdir: /opt/jenkins
